vich_uploader:
  db_driver: orm

  mappings:
    swipe_background:
      uri_prefix: /assets/uploaded/swipe_images
      upload_destination: '%kernel.project_dir%/public/assets/uploaded/swipe_images'
      namer:
        service: Vich\UploaderBundle\Naming\HashNamer
        options: { algorithm: 'sha256', length: 50 }
      delete_on_remove: true
    swipe_logo:
      uri_prefix: /assets/uploaded/swipe_logo
      upload_destination: '%kernel.project_dir%/public/assets/uploaded/swipe_logo'
      namer:
        service: Vich\UploaderBundle\Naming\HashNamer
        options: { algorithm: 'sha256', length: 50 }
      delete_on_remove: true