vich_uploader:
  db_driver: orm

  mappings:
    swipe:
      uri_prefix: /assets/images/swipe_images
      upload_destination: '%kernel.project_dir%/public/assets/images/swipe_images'
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options: { property: 'id' }
      delete_on_remove: true