version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
###< doctrine/doctrine-bundle ###

  adminer:
    image: adminer
    restart: always
    ports:
        - "666:8080"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
